### PR TITLE
Hotfix/solve redis conditional issue

### PR DESCRIPTION
**Pull request by yozzo**

### CODE REVIEW

**Comment by yozzo** [comment]
tests fail because redis isn’t running on CI at all, and it’s not a config issue - it’s the workaround we removed. but the ci redis matter needs adressing

**Comment by web-bert** [comment]
Adding `- *docker_redis` to the `unit_test` job in config.yml for CircleCI should fix it?

**Comment by PippoRaimondi** [comment]
> Adding `- *docker_redis` to the `unit_test` job in config.yml for CircleCI should fix it?

That would mean that we would need redis locally too if we want to run unit tests... doesn't feel right... not sure how that conditional went wrong... either way the correct thing to do is probably go for mocking redis or if it makes sense make it as a dependency injection... lets try the former option first...

**Comment by PippoRaimondi** [comment]
Oh boy... This is the problem in the conditional: `isCacheEnabled` .... same typo we fixed in the other file...

**Comment by web-bert** [comment]
I guess I always have Redis running so it's not an issue for me, but it feels wrong to add logic just for testing? The real issue is that app.spec.js tests the app routes by running the app and calling the routes. Maybe that should be split out so we can run the main unit tests without the need for Redis - although it still needs to run the app.spec to get the coverage up and ensure all the routes are configured correctly.

Ah I see: `isCachingEnabled` vs `isCacheEnabled`

**Comment by PippoRaimondi** [comment]
> I guess I always have Redis running so it's not an issue for me, but it feels wrong to add logic just for testing? The real issue is that app.spec.js tests the app routes by running the app and calling the routes. Maybe that should be split out so we can run the main unit tests without the need for Redis - although it still needs to run the app.spec to get the coverage up and ensure all the routes are configured correctly.
> 
> Ah I see: `isCachingEnabled` vs `isCacheEnabled`

Not sure if it's a right or wrong thing but more of a preference... I see no issues adding logic/code to facilitate testing if there isn't an alternative, in this case mocking redis is an alternative... maybe a quick fix is get the conditional right... and then mock redis out and get rid of that logic...

**Comment by PippoRaimondi** [comment]
closing this PR as it's no longer needed!

**Pull request closed without merging**
